# Default values for lago-wrapper-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Target namespace — pass to helm install with: --namespace lago-ns
namespace: lago-ns

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: nginx
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - chart-example.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

global:
  security:
    allowInsecureImages: true

postgresql:
  image:
    registry: docker.io
    repository: getlago/postgres-partman
    tag: "15.0-alpine"
  auth:
    username: lago
    password: password
    database: lago

redis:
  auth:
    enabled: true
    password: "lagoredis"

lago:
  migrate:
    enabled: true
  global:
    urls:
      api: "http://localhost:3001"
      front: "http://localhost:3000"

    database:
      uri: "postgres://lago:password@lago-wrapper-app-postgresql.lago-ns.svc.cluster.local:5432/lago"

    redis:
      uri: "redis://:lagoredis@lago-wrapper-app-redis-master.lago-ns.svc.cluster.local:6379"
    redisCache:
      uri: "redis://:lagoredis@lago-wrapper-app-redis-master.lago-ns.svc.cluster.local:6379"
    redisStore:
      uri: "redis://:lagoredis@lago-wrapper-app-redis-master.lago-ns.svc.cluster.local:6379"

    # WARNING: generate once and never change — changing these makes encrypted data unreadable
    # Generate with: openssl rand -hex 16
    encryption:
      key: "71669fdeee5b877686c7ab19e9e05adc"
      salt: "76f5b3f8b147293349c0e2ce90ecc71b"

    # Generate rsa with: openssl genrsa 2048 | openssl base64 -A
    # Generate hmac with: openssl rand -base64 16
    signing:
      rsa: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRGp6d0JHOEgxSEFobFUKNCtBWi9KdU55OW55SUJuNU1vdzlJMjN1eGxhdnFjZmpuK2hMK0NPNGVmQnhkZzZTbkx3ODIxREJOR2EyeThjVQp4d2YxYjJGRmZvaVJtWlNlano4ajZKdk1FZjdFRTRpQXVxR2orSW9KRk50RHFiQ1Y1bUFpRjg3RExXMWxISHF5ClIvc0lXZ25zQUtOdlNzOWdSbXFXVVZoQUdvVWtZUGVrcVloL05yR1NsazkzSU84TVNjdlZNS2crMWs3WFJrL0sKUjJDSFFLSVdidlBmck1GNEpHWWJvV21yNmpWVTNaSVJZRW5zOUxEeWNLSUtGVjJaRkdJOGRTL01FeEE0WTlWNwowRU56Sk9hdmVNQ2FwSTJuVzR6Y2xQVkFkTFNha1VDQnRCS0F6aXI2VmRHeDhuU1R2UEZQSGNNVURqRTJNOU9WCno0dVVGRjc5QWdNQkFBRUNnZ0VBT1p0RVlpdjVPZ1lWV3NxZkJtTkRBTG5lWEtSeWZQb2p6V2dTcWhFOHBZSWsKK25JYTMyOFp0Vkljazh4N1JlYmRrUFFTdVRDamtyRDRJRkJ1T2tuV2lxakRKekp6aXg4RkkvTHp4c2g4S0tBWgo0aGVQdlhPaGtFZFdaUWRaa0tabmcrZUtVUC9CVEpMRmtpU3luYnVMQzhOamtNYVZweTVYVUxpMFBNMllBb2tLCm5CUGY5WE9SN2t4cXA1dytIMmRXSXQzRVVoVHpMa2FiMk5kd1lRbEd4ZnFjNlJEQmhkak5NVzF1T1J1MmZFUlEKU0Qza2l1MzA0eUJOMzl4TURranpmL2VGQkRpUDhudWhwZGo0V0pPaE02NEZVbjhmd2g3TlhQQWR2dkd2YzY1TgpYMDg4U1RxVTNEd0MrSFlnL0pVWjVCbHA0QXRmcllURk5WekJ6ekozdndLQmdRRDI0aGNRWUhIQWpkR2NxM2NtCnhDdW5sODVUTVRmNnhhcTZyYy9sN0RBSFZ0TUhIZmN3RUllcW1reUo3WkU4TkxvdDc5Zk80cGFFbVBwNDFMTGQKQTY4SlNOL3kxU1ZNdG0zUzJBWDJoaDhwOWJHbytCaFlEOVp4WEJOTndCUUZOdnZndWxhdGNuTklHN2xSZU1aVQorMWtOdTd3bmR5RjE4QUJ4QWdzZ0FDc3B0d0tCZ1FEc09KYnUwOVdJbnNleUozSGVDWFRjcVdTWm9FRmEycmdXCnFSb2VzZDdRS1VVc3RLVmd2SXRJdkhKRWtUd1p5Z1BhMGJ6TnkxZk4xM3czWHdNMWxmV294TkxoZVc4Ui9LSmkKYThUVVJEY0djV3RSN011OWRHSlo3Nmhjd2tiZDJVZTBVK1VQR2FvYkwzclVrdGVlc1RSelp2YzFHUWd6ZXBkSgpiVS9TVDRPTTZ3S0JnQXJGSkRKdnNxYXV5U1VuaWNRa0xLOWIvUUUrRlc0WUwzR0RZWjFySjFFNnBXd2JENHlHClBCVGlORktVRFpEdHorMXZHQ0FMWEh1ZVhOYm1tSUx4eFRJSGZ0V09ITmx5MyttaHlPalBRdzdHakNDTjZpbjEKVHVxVkZMYUFtWjc4bmhKWXJxMVVYOWtXZElnc1Y2S2ZjR3diODRKWlBSbHpCZUhvTCtvT2Q5T1RBb0dCQUpnaApiZHNMNUVhamM1cWgycXlUeklaY05hVFcxNkJLb2lvOTU4dUM1Q3VObUxaTTlRRVRER1Rnc0hyR1NqMlZvOXZtCkhjRXZ4ekdUS0xXRVpFMjdjVVdxMU9GUFVwL3o0eVNkb1ZyUFA5elBhTDJQVWp1R1c5enVBckVTa1k5STR1d1kKNTdsTTN3ZTVFVk1iNnUrUjBtVE1HRU5EQnN3WWxKdytZUnppQnFmWEFvR0JBTmJpK3ZsaFJFbHd1LzQ2ZFlMZwpZWmRyRERvOFFubExwUzFhTkxEWkxraG9HWUNVZDRNQkpOSkVpMlNNbHp6S0w3VVBmZ0xYbzgydjNJazJ0TzBLCkdRbUcrT3czaFZVMUdDTVNXWExxSHZQaGQvSkFyUnRXc3RyRFlmd3dNOUtFdTRFZ1ArdVFrQVh1ZVRURDRjQXcKaU9HaWoyQ1NIYmxQeVcrL2FYajdFYkM1Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
      hmac: "+q1OyAJUB0ytlWeHFuzhnw=="
